export const PRODUCT_REQUEST='PRODUCT_REQUEST';
export const PRODUCT_REQUEST_SUCCESS='PRODUCT_REQUEST_SUCCESS';
export const GET_ONE_PRODUCT='GET_ONE_PRODUCT';
export const WISH_LIST_REQUEST='WISH_LIST_REQUEST';
export const WISH_LIST_SUCCESS='WISH_LIST_SUCCESS';
export const WISH_LIST_GET_REQUEST='WISH_LIST_GET_REQUEST';
export const WISH_LIST_GET_SUCCESS='WISH_LIST_GET_SUCCESS';
export const GET_PRODUCT_CATAGORY_REQUEST='GET_PRODUCT_CATAGORY_REQUEST';
export const GET_PRODUCT_CATAGORY_SUCCESS='GET_PRODUCT_CATAGORY_SUCCESS';
// user 
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILE='LOGIN_FAILE';
export const GET_USER_REQUEST='GET_USER_REQUEST';
export const GET_USER_SUCCESS='GET_USER_SUCCESS';
export const USER_UPDATE_REQUEST='USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS='USER_UPDATE_SUCCESS';
export const LOGOUT_REQUEST='LOGOUT_REQUEST';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
// user end

// catagory start
export const CATAGORY_GET_REQUEST='CATAGORY_GET_REQUEST';
export const CATAGORY_GET_SUCCESS='CATAGORY_GET_SUCCESS';
// catagory ending

// Bid
export const BID_REQUEST='BID_REQUEST';
export const BID_SUCCESS='BID_SUCCESS';
export const GET_BID_REQUEST='GET_BID_REQUEST';
export const GET_BID_SUCCESS='GET_BID_SUCCESS';
export const VIEW_AUCTION_REQUEST='VIEW_AUCTION_REQUEST';
export const VIEW_AUCTION_SUCCESS='VIEW_AUCTION_SUCCESS';
// Bid Ending